description: "This project is developed from training materials for researchers wanting to learn to build websites in GitHub wiht GitHub Pages."
email: "team@carpentries.org"
github: "https://github.com/annadyaung/group-website.git"
